version: '3.8'

services:
    ilyaguev_igor-indigolab-php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: ilyaguev_igor-indigolab-php
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        environment:
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ilyaguev_igor-indigolab-postgres:5432/${POSTGRES_DB}
            - REDIS_URL=redis://ilyaguev_igor-indigolab-redis:6379
#            - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST}
#            - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
        depends_on:
            - ilyaguev_igor-indigolab-postgres
            - ilyaguev_igor-indigolab-redis
        networks:
            - indigolab-network

    ilyaguev_igor-indigolab-nginx:
        image: nginx:latest
        container_name: ilyaguev_igor-indigolab-nginx
        restart: unless-stopped
        ports:
            - "${HTTP_PORT}:80"
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html/public
        depends_on:
            - ilyaguev_igor-indigolab-php
        networks:
            - indigolab-network

    ilyaguev_igor-indigolab-postgres:
        image: postgres:latest
        container_name: ilyaguev_igor-indigolab-postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
            TZ: "Europe/Moscow"
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - ./docker/pgdata:/var/lib/postgresql/data
        networks:
            - indigolab-network

    ilyaguev_igor-indigolab-redis:
        image: redis:latest
        container_name: ilyaguev_igor-indigolab-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - indigolab-network

volumes:
    postgres_data:

networks:
    indigolab-network:
        driver: bridge
